name = "RiemannianCoupledGPERotation"
uuid = "3b195bb6-c47d-47d5-915e-0a5a58f6a6c4"
authors = ["Martin Hermann <maahermann@aol.de>"]
version = "0.1.0"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
IncompleteLU = "40713840-3770-5561-ab4c-a76e7d0d7895"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
